using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Ubiety.Nbt.Generators;

/// <summary>
/// Writes the source for a <see cref="ContextModel"/>.
/// </summary>
internal static class Emitter
{
    private const string Metadata = "global::Ubiety.Nbt.Serialization.Metadata";
    private const string Compound = "global::Ubiety.Nbt.NbtCompound";
    private const string State = Metadata + ".NbtSerializationState";
    private const string UnsafeAccessor = "global::System.Runtime.CompilerServices.UnsafeAccessor";
    private const string UnsafeAccessorKind = "global::System.Runtime.CompilerServices.UnsafeAccessorKind";

    public static string Emit(ContextModel model)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable disable");
        w.Line("#pragma warning disable CS0612, CS0618");
        w.Line();

        if (model.Namespace is not null)
        {
            w.Line($"namespace {model.Namespace}");
            w.Open();
        }

        var context = model.ClassName;
        w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"Ubiety.Nbt.Generators\", \"1.0.0\")]");
        w.Line($"partial class {context}");
        w.Open();

        w.Line($"private static {context} __default;");
        w.Line();
        w.Line("/// <summary>Gets the default instance, which uses the default options.</summary>");
        w.Line($"public static {context} Default => __default ??= new {context}();");
        w.Line();
        w.Line($"/// <summary>Initializes a new instance of the <see cref=\"{context}\"/> class with the default options.</summary>");
        w.Line($"public {context}()");
        w.Line("    : base(null)");
        w.Line("{");
        w.Line("}");
        w.Line();
        w.Line($"/// <summary>Initializes a new instance of the <see cref=\"{context}\"/> class.</summary>");
        w.Line("/// <param name=\"options\">The options.</param>");
        w.Line($"public {context}(global::Ubiety.Nbt.Serialization.NbtSerializerOptions options)");
        w.Line("    : base(options)");
        w.Line("{");
        w.Line("}");

        foreach (var type in model.Types)
        {
            var access = type.IsPublic ? "public" : "internal";
            w.Line();
            w.Line($"private {Metadata}.NbtTypeInfo<{type.FullName}> __{type.PropertyName};");
            w.Line();
            w.Line($"/// <summary>Gets the metadata for <c>{Xml(type.FullName)}</c>.</summary>");
            w.Line($"{access} {Metadata}.NbtTypeInfo<{type.FullName}> {type.PropertyName} => __{type.PropertyName} ??= {CreateExpression(type)};");
        }

        w.Line();
        w.Line("/// <inheritdoc/>");
        w.Line($"public override {Metadata}.NbtTypeInfo GetTypeInfo(global::System.Type type)");
        w.Open();
        foreach (var type in model.Types)
        {
            w.Line($"if (type == typeof({type.FullName})) return {type.PropertyName};");
        }

        w.Line("return null;");
        w.Close();

        foreach (var type in model.Types.Where(t => t.Object is not null))
        {
            w.Line();
            EmitObjectInfo(w, context, type, type.Object!);
        }

        w.Close();
        if (model.Namespace is not null)
        {
            w.Close();
        }

        return w.ToString();
    }

    private static string CreateExpression(TypeModel type) => type.Kind switch
    {
        TypeModelKind.Primitive => $"{Metadata}.NbtMetadata.{type.Primitive}",
        TypeModelKind.Tag => $"{Metadata}.NbtMetadata.CreateTagInfo<{type.FullName}>()",
        TypeModelKind.Enum => $"{Metadata}.NbtMetadata.CreateEnumInfo<{type.FullName}>(Options)",
        TypeModelKind.Nullable => $"{Metadata}.NbtMetadata.CreateNullableInfo<{type.ElementFullName}>(Options, {type.ElementProperty})",
        TypeModelKind.Array => $"{Metadata}.NbtMetadata.CreateArrayInfo<{type.ElementFullName}>(Options, {type.ElementProperty})",
        TypeModelKind.List => $"{Metadata}.NbtMetadata.CreateListInfo<{type.FullName}, {type.ElementFullName}>(Options, {type.ElementProperty})",
        TypeModelKind.Dictionary => $"{Metadata}.NbtMetadata.CreateDictionaryInfo<{type.FullName}, {type.ElementFullName}>(Options, {type.ElementProperty})",
        _ => $"new __{type.PropertyName}Info(this)",
    };

    private static void EmitObjectInfo(CodeWriter w, string context, TypeModel type, ObjectModel model)
    {
        var members = model.Members;
        var t = type.FullName;
        var className = $"__{type.PropertyName}Info";

        w.Line($"private sealed class {className} : {Metadata}.NbtObjectInfo<{t}>");
        w.Open();
        w.Line($"private readonly {context} _context;");
        for (var i = 0; i < members.Length; i++)
        {
            w.Line($"private readonly string __key{i};");
        }

        w.Line();
        w.Line($"public {className}({context} context)");
        w.Line("    : base(context.Options)");
        w.Open();
        w.Line("_context = context;");
        for (var i = 0; i < members.Length; i++)
        {
            var explicitName = members[i].ExplicitName is { } name ? Literal(name) : "null";
            w.Line($"__key{i} = GetKey({Literal(members[i].Name)}, {explicitName});");
        }

        w.Close();

        EmitWriteMembers(w, t, members);
        EmitReadMembers(w, t, model);
        EmitAccessors(w, t, model);
        w.Close();
    }

    private static void EmitWriteMembers(CodeWriter w, string t, EquatableArray<MemberModel> members)
    {
        w.Line();
        w.Line($"protected override void WriteMembers({t} value, {Compound} compound, {State} state)");
        w.Open();
        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            var receiver = member.DeclaringTypeIsValueType ? "ref value" : "value";
            var get = member.Get switch
            {
                AccessMode.Accessor when member.IsField => $"__field{i}({receiver})",
                AccessMode.Accessor => $"__get{i}({receiver})",
                _ => $"value.{Escape(member.Name)}",
            };

            var info = $"_context.{member.InfoProperty}";
            w.Line($"{member.TypeFullName} __m{i} = {get};");
            if (member.IsNullableValueType)
            {
                w.Line($"if (__m{i}.HasValue) state.WriteMember(compound, __key{i}, __m{i}.GetValueOrDefault(), {info});");
            }
            else if (member.IsReferenceType)
            {
                w.Line($"if (__m{i} is not null) state.WriteMember(compound, __key{i}, __m{i}, {info});");
            }
            else
            {
                w.Line($"state.WriteMember(compound, __key{i}, __m{i}, {info});");
            }
        }

        w.Close();
    }

    private static void EmitReadMembers(CodeWriter w, string t, ObjectModel model)
    {
        var members = model.Members;
        var parameters = model.Constructor?.Parameters ?? default;
        var boundTo = new Dictionary<int, int>();
        for (var j = 0; j < parameters.Length; j++)
        {
            boundTo[parameters[j].MemberIndex] = j;
        }

        w.Line();
        w.Line($"protected override {t} ReadMembers({Compound} compound, {State} state)");
        w.Open();

        // Read in the same order as the reflection serializer, so errors are reported identically.
        for (var j = 0; j < parameters.Length; j++)
        {
            var p = parameters[j];
            w.Line($"bool __hasP{j} = state.TryReadMember(compound, __key{p.MemberIndex}, _context.{p.InfoProperty}, out {p.InfoTypeFullName} __p{j});");
            if (members[p.MemberIndex].IsRequired && p.DefaultLiteral is null)
            {
                w.Line($"if (!__hasP{j}) throw state.MissingRequired(__key{p.MemberIndex});");
            }
        }

        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            if (boundTo.ContainsKey(i) || member.Set == AccessMode.None)
            {
                continue;
            }

            w.Line($"bool __has{i} = state.TryReadMember(compound, __key{i}, _context.{member.InfoProperty}, out {member.InfoTypeFullName} __v{i});");
            if (member.IsRequired)
            {
                w.Line($"if (!__has{i}) throw state.MissingRequired(__key{i});");
            }
        }

        var arguments = new List<string>();
        for (var j = 0; j < parameters.Length; j++)
        {
            var p = parameters[j];
            arguments.Add($"__hasP{j} ? ({p.TypeFullName})__p{j} : {p.DefaultLiteral ?? $"default({p.TypeFullName})"}");
        }

        var initializers = new List<string>();
        for (var i = 0; i < members.Length; i++)
        {
            if (members[i].Set == AccessMode.Initializer)
            {
                var value = boundTo.TryGetValue(i, out var j) ? arguments[j] : $"__v{i}";
                initializers.Add($"{Escape(members[i].Name)} = {value}");
            }
        }

        var construct = model.Constructor is { IsAccessible: false }
            ? $"__ctor({string.Join(", ", arguments)})"
            : $"new {t}({string.Join(", ", arguments)})";
        if (initializers.Count > 0)
        {
            construct += " { " + string.Join(", ", initializers) + " }";
        }

        w.Line($"{t} __obj = {construct};");

        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            if (boundTo.ContainsKey(i) || member.Set is AccessMode.None or AccessMode.Initializer)
            {
                continue;
            }

            var receiver = member.DeclaringTypeIsValueType ? "ref __obj" : "__obj";
            var assignment = member.Set switch
            {
                AccessMode.Accessor when member.IsField => $"__field{i}({receiver}) = __v{i};",
                AccessMode.Accessor => $"__set{i}({receiver}, __v{i});",
                _ => $"__obj.{Escape(member.Name)} = __v{i};",
            };

            w.Line($"if (__has{i}) {assignment}");
        }

        w.Line("return __obj;");
        w.Close();
    }

    private static void EmitAccessors(CodeWriter w, string t, ObjectModel model)
    {
        var members = model.Members;
        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            var receiver = (member.DeclaringTypeIsValueType ? "ref " : string.Empty) + member.DeclaringTypeFullName + " obj";

            if (member.IsField && (member.Get == AccessMode.Accessor || member.Set == AccessMode.Accessor))
            {
                w.Line();
                w.Line($"[{UnsafeAccessor}({UnsafeAccessorKind}.Field, Name = {Literal(member.Name)})]");
                w.Line($"private static extern ref {member.TypeFullName} __field{i}({receiver});");
                continue;
            }

            if (member.Get == AccessMode.Accessor)
            {
                w.Line();
                w.Line($"[{UnsafeAccessor}({UnsafeAccessorKind}.Method, Name = {Literal(member.GetterName!)})]");
                w.Line($"private static extern {member.TypeFullName} __get{i}({receiver});");
            }

            if (member.Set == AccessMode.Accessor)
            {
                w.Line();
                w.Line($"[{UnsafeAccessor}({UnsafeAccessorKind}.Method, Name = {Literal(member.SetterName!)})]");
                w.Line($"private static extern void __set{i}({receiver}, {member.TypeFullName} value);");
            }
        }

        if (model.Constructor is { IsAccessible: false } constructor)
        {
            var parameters = string.Join(", ", constructor.Parameters.Select((p, j) => $"{p.TypeFullName} p{j}"));
            w.Line();
            w.Line($"[{UnsafeAccessor}({UnsafeAccessorKind}.Constructor)]");
            w.Line($"private static extern {t} __ctor({parameters});");
        }
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Escape(string name) =>
        SyntaxFacts.IsReservedKeyword(SyntaxFacts.GetKeywordKind(name)) ? "@" + name : name;

    private static string Xml(string text) => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private sealed class CodeWriter
    {
        private readonly StringBuilder _builder = new();
        private int _indent;

        public void Line(string text = "")
        {
            if (text.Length > 0)
            {
                _builder.Append(' ', _indent * 4);
            }

            _builder.Append(text).Append('\n');
        }

        public void Open()
        {
            Line("{");
            _indent++;
        }

        public void Close()
        {
            _indent--;
            Line("}");
        }

        public override string ToString() => _builder.ToString();
    }
}
